[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints= {sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/g7yTS0d533h3UaHk_7jdJ", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/g7yTS0d533h3UaHk_7jdJ"}
via_ir = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    '@ccip/=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
